---
name: Testing
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      dists:
        type: string
        required: false
        default: "ubuntu-22.04"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Generates build matrix
        id: generate_matrix
        run: |-
          declare -a dists=()

          for i in $(echo "ubuntu-22.04, debian-12" | tr "," " ")
          do
            dists+=($i)
          done

          JO="$(jo -a ${dists[*]})"
          output="{\"os\": $JO }"
          echo "matrix=${output}" >> $GITHUB_OUTPUT

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .

  molecule:
    name: Molecule
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.lint.outputs.matrix) }}
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip

      - name: Install test dependencies.
        run:
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DIST: ${{ matrix.os }}
